trigger:
  - main  # Cambia esto si tu rama principal tiene otro nombre

pool:
  name: Default

variables:
  buildConfiguration: 'Release'

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.0.x'  # Ajusta según la versión de .NET que uses
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: dotnet restore
    displayName: 'Restaurar paquetes NuGet'

  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'Compilar aplicación'

  - script: dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
    displayName: 'Publicar aplicación'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'aspnetapp'
      publishLocation: 'Container'
